# Prediction

In [15]:
import numpy as np
import pandas as pd
import joblib

#### Gọi lại 2 models

In [16]:
from model_classes import LinearRegression, ZScoreNormalizer

In [17]:
model = joblib.load("models/linear_model.pkl")
normalizer = joblib.load("models/normalizer.pkl")

#### Tạo cột dự đoán

In [18]:
feature_columns = [
    "Number_of_Customers_Per_Day",
    "Average_Order_Value",
    "Operating_Hours_Per_Day",
    "Number_of_Employees",
    "Marketing_Spend_Per_Day",
    "Location_Foot_Traffic"
]

#### Lấy giá trị trung bình của từng cột làm typical

In [31]:
df = pd.read_csv("coffee_shop_revenue_cleaned.csv")

In [33]:
mean_values = df.mean()

print(mean_values)

number_of_customers_per_day     274.296000
average_order_value               6.261215
operating_hours_per_day          11.667000
number_of_employees               7.947000
marketing_spend_per_day         252.614160
location_foot_traffic           534.893500
daily_revenue                  1917.325940
dtype: float64

In [34]:
new_cases = pd.DataFrame([
    [274, 6.3, 12, 8, 253, 535],  # Case 1: Typical
    [400, 6.3, 12, 8, 253, 535],  # Case 2: More Customers
    [275, 9.0, 12, 8, 253, 535],  # Case 3: Higher Order Value
    [275, 6.3, 12, 8, 450, 535]   # Case 4: Higher Marketing
], columns=feature_columns)

#### Chuẩn hóa

In [35]:
X_new = new_cases[feature_columns]

X_new_scaled = normalizer.transform(X_new)

X_new_scaled

,Number_of_Customers_Per_Day,Average_Order_Value,Operating_Hours_Per_Day,Number_of_Employees,Marketing_Spend_Per_Day,Location_Foot_Traffic
0,0.026968,-0.003987,0.049843,-0.033167,0.023938,0.057779
1,0.992311,-0.003987,0.049843,-0.033167,0.023938,0.057779
2,0.034630,1.226433,0.049843,-0.033167,0.023938,0.057779
3,0.034630,-0.003987,0.049843,-0.033167,1.471259,0.057779

#### Dự đoán

In [36]:
predictions = model.predict(X_new_scaled)

predictions

0    1929.634042
1    2617.518616
2    2581.292684
3    2245.119751
dtype: float64

In [37]:
new_cases["Predicted_Daily_Revenue"] = predictions

new_cases

,Number_of_Customers_Per_Day,Average_Order_Value,Operating_Hours_Per_Day,Number_of_Employees,Marketing_Spend_Per_Day,Location_Foot_Traffic,Predicted_Daily_Revenue
0,274,6.3,12,8,253,535,1929.634042
1,400,6.3,12,8,253,535,2617.518616
2,275,9.0,12,8,253,535,2581.292684
3,275,6.3,12,8,450,535,2245.119751